-- Create projects table to manage native, github-connected, or external projects
-- Uses text IDs generated by the app (crypto.randomUUID) to avoid extension dependencies.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  type VARCHAR(20) NOT NULL DEFAULT 'native', -- native | github | external
  repo_url TEXT,
  metadata JSONB,
  pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Helpful indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_repo_url ON projects((lower(repo_url))) WHERE repo_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_projects_pinned ON projects(pinned);
CREATE INDEX IF NOT EXISTS idx_projects_name ON projects((lower(name)));

-- Trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
