-- Create projects table to manage native, github-connected, or external projects
-- Uses text IDs generated by the app (crypto.randomUUID) to avoid extension dependencies.

create table if not exists projects (
  id uuid primary key,
  name text not null,
  description text,
  type text not null check (type in ('native', 'github', 'external')),
  repo_url text,
  metadata jsonb not null default '{}'::jsonb,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Helpful index for sorting/filtering
create index if not exists idx_projects_pinned_created_at on projects (pinned desc, created_at desc);

-- Trigger to auto-update updated_at
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_projects_updated_at on projects;
create trigger trg_projects_updated_at
before update on projects
for each row
execute function set_updated_at();
